; PlatformIO Project Configuration File
;
;   Ocean Atlas – NodeMCU ESP32-S multi-sensor firmware
;   Board   : esp32dev (NodeMCU ESP32-S)
;   Framework: Arduino
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board    = esp32dev
framework = arduino

monitor_speed  = 115200
upload_port    = COM7
upload_speed   = 921600
monitor_port   = COM7

lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    arduino-libraries/LiquidCrystal @ ^1.0.7
